### ISSUE TITLE
How to Get Rows Updated when executing Insert Command

### ISSUE THREAD

**Issue by vnnv01** [pacman82/odbc-sys#17]
I am trying to insert a record in to table using select statement and I want to know how many records inserted. I am not able to get the results using cursor. Is there any other ways to get number of records affected in ODBC

**Comment by pacman82** [comment]
#16 has been merged and released. Does this help your use case?

**Comment by Koka** [comment]
We need some additional work on odbc-safe and odbc crates, but looks like all work here is done, thanks
