### ISSUE TITLE
SQLPutData support

### ISSUE THREAD

**Issue by cquintana-verbio** [pacman82/odbc-sys#28]
Hi!
First of all, thanks for your library.

We are trying to use another library that depends on this one (odbc-rs) in order to connect to an Oracle Database.

Due to how Oracle Databases work with BLOB types (they cap at 2kb for a bind_parameter), one needs to use the SQLPutData method:

https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlputdata-function?view=sql-server-ver15

However, the library does not expose it.

Is there any reason? Is it planned to be supported in the future?

Thanks!

**Comment by pacman82** [comment]
No it is just missing, no deeper reason. Added it in `0.12.2`. You are welcome.
