### ISSUE TITLE
SqlReturn uses incorrect value

### ISSUE THREAD

**Issue by Sineaggi** [pacman82/odbc-sys#31]
In pr #27 SqlReturn changed
```    SQL_INVALID_HANDLE = -2,```
to     ```pub const INVALID_HANDLE: SqlReturn = SqlReturn(-1);```

Is this correct?

**Comment by pacman82** [comment]
Thanks for politely phrasing it as a question, but no this is an accidental change. I screwed up. The downstream libraries pretty much prevent INVALID HANDLES by design, how on earth did you find this? Luckily it should not be to hard to write a test for this to prevent that error in the future.

**Comment by pacman82** [comment]
Fixed in 0.17.1. Thanks for reporting!
