### ISSUE TITLE
no example 

### ISSUE THREAD

**Issue by haochiya** [pacman82/odbc-sys#33]
Hi,
I need to get a simple example to use this crate.
1 connect any DB
2 execute SQL
HELP please.

**Comment by pacman82** [comment]
Hi @haochiya ,

I wouldn't recommend using these crate directly in an application, as it just contains raw bindings to the C-API. It's very hard to use directly without having a solid understanding of ODBC API and how to work with unsafe code. Even than it is not fun.

Luckily you do not have to. I highly recommend using the `odbc-api` crate instead (<https://github.com/pacman82/odbc-api>). It contains higher level bindings build on top of this one. I hope the guide provides a good starting point in terms of documenation: <https://github.com/pacman82/odbc-api>.

**Comment by haochiya** [comment]
Thank you for your answer and your good work!
