### ISSUE TITLE
target_value_ptr of SQLGetData return  0x0

### ISSUE THREAD

**Issue by haochiya** [pacman82/odbc-sys#34]
Hi,
I want to use SQLGetData function  to get some data from mysql (ver:8) table.
But,target_value_ptr of SQLGetData always return  0x0 .Why?
All SqlReturn return success before using SQLGetData function.

Table name xxx
(
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb3 
 
Souce

>     
        let mut id = null_mut();
        let mut str_len = null_mut();
        loop {
            let rc1 = SQLFetch(stmt_handle as HStmt);
            if (SqlReturn::SUCCESS == rc1) || (SqlReturn::SUCCESS_WITH_INFO == rc1) {
                let subrc = SQLGetData(
                          stmt_handle as HStmt,
                           1 as u16,
                           CDataType::SLong,
                           id,
                           8,
                           str_len as *mut isize
                );
                println!("{:?},{:?},{:?}",subrc,id,str_len);
	        } else {
                break;
             }
        }

Result
SqlReturn(-1),0x0,0x0
SqlReturn(-1),0x0,0x0

**Comment by pacman82** [comment]
Hello @haochiya ,

why do you not use `odbc_api`?

```rust
fn print_ids(conn: &mut Connection<'_>) -> Result<(), Error> {
     let mut cursor = conn
         .execute("SELECT id FROM xxx", ())?
         .expect("Assume select statement creates cursor");
     while let Some(mut row) = cursor.next_row()? {
         let mut id = 0i64;
         row.get_data(1, &mut id)?;
         println!("ID: {}", id);
     } 
     Ok(())
 }
```

**Comment by pacman82** [comment]
> By the way, there is an error about fn print_ids.

This should not be an `Option`. The `.expect()` has been supposed to unwrap that.

**Comment by pacman82** [comment]
With regards to opening issues about using `odbc-sys`: Please kindly consider looking into https://docs.microsoft.com/en-us/sql/odbc/reference/odbc-programmer-s-reference?view=sql-server-ver15 first.
