### ISSUE TITLE
Open to extensions required to write an ODBC driver?

### ISSUE THREAD

**Issue by lfrancke** [pacman82/odbc-sys#42]
Hi,

I'm wondering if you're open to extending this crate with additional information / code required to implement ODBC drivers as opposed to applications calling ODBC functions.

I have listed two simple examples below but I'm sure I'll come up with more.
I'd be happy to send PRs but as they are obviously a lot of work I wanted to make sure that you'd be willing to accept something along those lines _in principle_. I understand if not as it clutters this library but as it concerns the core types mostly it can't be easily moved elsewhere.

### Example 1

```rust
pub fn SQLAllocHandle(
    handle_type: u16,
    input_handle: *mut c_void,
    output_handle: *mut *mut c_void,
) -> SqlReturn
```

In the driver I do not want `handle_type` to take a `HandleType` so I can handle a potential error in case an invalid value is passed in.
The Rust behaviour is undefined here (converting an undefined u16 to the enum). I'm currently using `TryFromPrimitive` from the [num_enum](https://crates.io/crates/num_enum) crate for that: 

```rust
use num_enum::TryFromPrimitive;

#[repr(i16)]
#[derive(Debug, PartialEq, Eq, Clone, Copy, TryFromPrimitive)]
pub enum HandleType {
    Env = 1,
    Dbc = 2,
    Stmt = 3,
    Desc = 4,
}
```

### Example 2

Another example is the `InfoType` which requires information about the expected return type for each variant.

Example snippet:

```rust
impl InfoType {
    pub fn return_type(&self) -> InfoTypeTypeInformation {
        match self {
            InfoType::MaxDriverConnections => InfoTypeTypeInformation::SqlUSmallInt,
            InfoType::MaxConcurrentActivities => InfoTypeTypeInformation::SqlUSmallInt,
            InfoType::DataSourceName => InfoTypeTypeInformation::String,
            InfoType::ServerName => InfoTypeTypeInformation::String,
[...]
```

**Comment by pacman82** [comment]
Hello @lfrancke ,

thanks for reaching out. I am open to changing `odbc-sys` so it enbles writing drivers as well as application. If we have to include breaking changes and sacrifice a bit of type safety so be it. Still I have some feedback to your suggestions:

> The Rust behaviour is undefined here (converting an undefined u16 to the enum).

In order to avoid that this crate does avoid using enums whenever a number is also an output of a function. However it does not just use a plain primitive e.g. `u16` so far, but a strict type alias, with the enum variants translated to constants. For an example look at `SqlReturn`: <https://github.com/pacman82/odbc-sys/blob/main/src/sqlreturn.rs>

```rust
/// Indicates the overall success or failure of the function
///
/// Each function in ODBC returns a code, known as its return code, which indicates the overall
/// success or failure of the function. Program logic is generally based on return codes.
/// See [ODBC reference](https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/return-codes-odbc)
#[must_use]
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
#[repr(C)]
pub struct SqlReturn(pub i16);

impl SqlReturn {
    /// `SQL_INVALID_HANDLE`; Function failed due to an invalid environment, connection, statement,
    /// or descriptor handle.
    ///
    /// This indicates a programming error. No additional information is available from
    /// `SQLGetDiagRec` or `SQLGetDiagField`. This code is returned only when the handle is a null
    /// pointer or is the wrong type, such as when a statement handle is passed for an argument a
    /// connection handle.
    pub const INVALID_HANDLE: SqlReturn = SqlReturn(-2);
    
    /// ...
}
```

I think we should be able to support drivers while keeping a bit of type safety around the handle pointers.

Best, Markus

**Comment by pacman82** [comment]
Losing some type safety is fine, as most applications would should use the higher level `odbc-api` bindings anyway.
