### ISSUE TITLE
AttrOdbcVersion - ODBC 2/3.8/4 support

### ISSUE THREAD

**Issue by lfrancke** [pacman82/odbc-sys#48]
An outside application might call `SQLSetEnvAttr` with the argument `SQL_OV_ODBC2`.
Currently this is not part of the `AttrOdbcVersion` enum because you don't support ODBC2.
That's fair and reasonable for _applications_ but as a driver there is little choice over the incoming requests.

I didn't immediately open a PR for this to ask your opinion first: This is one example but there might be others down the line where a driver needs a method or a constant or whatever that is not applicable to the applications.

In this case I need the constant to then be able to say that it's not supported. The same goes for 3.8 and 4.0 which are currently behind a feature gate.

I hope the explanation makes sense?

My concrete ask:
- Add ODBC 2 to AttrOdbcVersion
- Make 3.8 & 4 available without feature gate

**Comment by pacman82** [comment]
Hello Lars,

with regards to `AttrOdbcVersion`: I am fine with adding it. If it is used as an **input** for a driver though. You may need to also account for it being a version not yet known (let's say ODBC 5). Providing a number not covered by the enumeration would be undefined behavior. I would therefore suggest to also make `AttrOdbcVersion` a strict alias wrapping a public integer which provides public constants in its implementation. This is at least the pattern I have choosen so far in this case for this crate.

Could you help me understand why the feature Gate hurts you? Would a single `driver` feature gate be acceptable which implies the other features?

Best, Markus

**Comment by lfrancke** [comment]
>  I would therefore suggest to also make AttrOdbcVersion a strict alias wrapping a public integer which provides public constants in its implementation. This is at least the pattern I have choosen so far in this case for this crate.

I'm afraid I don't understand. Can you point me at an example?

> Could you help me understand why the feature Gate hurts you? Would a single driver feature gate be acceptable which implies the other features?

It doesn't hurt, I can just use them. It'd just be "cleaner" (for the driver) without them but that's not a problem.

I will wait with any PRs for the outcome of our brainstorming in #47

**Comment by pacman82** [comment]
> I'm afraid I don't understand. Can you point me at an example?

```rust
/// ODBC verions
///
/// `OdbcVersion` attribute set with [`SQLSetEnvAttr`] to declare ODBC version
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub struct AttrOdbcVersion(pub i32);

impl AttrOdbcVersion {
    pub const ODBC_3: AttrOdbcVersion = AttrOdbcVersion(3);
    #[cfg(feature = "odbc_version_3_80")]
    pub const ODBC_3_80: AttrOdbcVersion = AttrOdbcVersion(380);
    #[cfg(feature = "odbc_version_4")]
    pub const ODBC_4_00: AttrOdbcVersion = AttrOdbcVersion(400);
}
```

If you want to use this, you can start from this branch: <https://github.com/pacman82/odbc-sys/tree/Odbc-version-as-strict-alias>

> It doesn't hurt, I can just use them. It'd just be "cleaner" (for the driver) without them but that's not a problem.

I think overall I must keep the feature gates, because if functions are missing in the system library linking may fail. This could cause applications not to link against `iodbc` not to link if they contain any 3.8 symbols. So giving them an option to exclude newer symbols is nice. The most recent version (3.8) also imlpies all previous ones. ODBC 4 is not finalized yet (to my knowledege). So the default should be fine.

**Comment by pacman82** [comment]
Finking about linking, I wonder again. Do you really link against the driver manager. Are you linking against e.g. `unixODBC`. Is not rather the driver manager linking against the driver you are writing?

If you are not linking against the driver manager having this **not** in `odbc-sys` is despite the similarity in signatures probably the right call.

Best, Markus

**Comment by lfrancke** [comment]
Ah! I understand now. Similar to how `SqlReturn` is structured. Sorry, I was a bit slow to understand.
Thank you for the branch!

Your second question is a good one. So far I was always using no features and I'm on linux so I assume it links against `unixODBC` but I have not tested the same driver file with `iodbc`. I can do that later.

ODBC4 is weird, the whole ODBC spec process is weird and....underdocumented....

**Comment by pacman82** [comment]
Closing this issue. Please feel free to reopen it, if there is something actionable to do, or a related idea to discuss.
